defaults:
  - dataset: ABCD
  - model: bnt # brainnetcnn, fbnetgen, bnt, transformer
  - optimizer: adam
  - training: basic_training
  - datasz: 100p
  - preprocess: mixup
  - _self_
repeat_time: 5
log_path: result
save_learnable_graph: False
save_attn_weights: True
save_test_attn_weights: False
# wandb
wandb_entity: minhengchen65-university-of-texas-at-arlington
project: brainnetworktransformer